### ISSUE TITLE
problem when the PDF includes a differential equation

### ISSUE THREAD

**Issue by itpamendola** [joshburkart/mathematica-mcmc#1]
## I tried working this example in Mathematica: 

Clear[plogexpr];
delta[x1_] := 
 NDSolve[{z'[t] == - x1*z[t], z[-1] == 1}, z, {t, -1, 0}][[1, 1, 2]]
plogexpr := -(delta[x1][0] - 1)^2;
Table[plogexpr, {x1, 0, 1, 1}];
mcmc = MCMC[plogexpr, {{x1, 0, 1, Reals}}, 100]

---
## When I run the Table, it works fine, but then MCMC complains that the diff eq is non-numerical; the problem is in the variable x1 being inside NDSolve, it seems it does not take a numerical value; if I remove the x1 from inside the NDSolve, eg

Clear[plogexpr];
delta := NDSolve[{z'[t] == - z[t], z[-1] == 1}, z, {t, -1, 0}][[1, 1,  2]]
plogexpr := -(delta[0] - x1)^2;
mcmc = MCMC[plogexpr, {{x1, 0, 1, Reals}}, 100]

---

then it works fine.
Any suggestion?

**Comment by joshburkart** [comment]
Does the following modification of your first example work?

```
Clear[plogexpr];
delta[x1_?NumericQ] := 
NDSolve[{z'[t] == - x1*z[t], z[-1] == 1}, z, {t, -1, 0}][[1, 1, 2]]
plogexpr = -(delta[x1][0] - 1)^2;
Table[plogexpr, {x1, 0, 1, 1}];
mcmc = MCMC[plogexpr, {{x1, 0, 1, Reals}}, 100]
```

When things get evaluated is a pretty standard Mathematica annoyance. :) Basically you don't want `delta[x]` to substitute the `NDSolve` call until `x` is actually a number.

**Comment by itpamendola** [comment]
yes, it works now, thank you so much!
